version: "{build}"

branches:
  only:
    - master

only_commits:
  message: /^\+/
  author: dejbug@users.noreply.github.com

test: off

clone_folder: c:\projects\$(appveyor_project_name)
shallow_clone: true
max_jobs: 1

# scripts that run after cloning repository
install:

# to run your custom scripts instead of automatic MSBuild
build_script:
  - echo %APPVEYOR_API_URL%
  - set PATH=C:\MinGW\bin;%PATH%
  - set PATH=C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\bin;%PATH%
  - mingw32-make --version | head -1
  - g++ --version | head -1
  - ar --version | head -1
  - cd build\msw
  - mingw32-make -j1 -f makefile.gcc CPPFLAGS=-Os SHARED=0 UNICODE=1 BUILD=release VENDOR=dejbug
  - echo libwxmsw31u.a : $(wildcard gcc_mswu/*.o) ; ar r $@ $(subst /,\,$^^) > monolib.makefile
  - mingw32-make -f -j1 monolib.makefile
  - python -c "import os,re; n = '%APPVEYOR_PROJECT_NAME%-' + re.search(r'(?m)^ *DYLIB_CURRENT_VERSION += +(.+) *$', open('..\osx\wxvers.xcconfig').read()).group(1); os.mkdir(n)"
  - cd wxWidgets-*
  - move ..\..\..\include .
  - mkdir lib
  - move ..\*.a lib
  - move ..\..\..\lib\gcc_lib\mswu lib
  - 7z a ..\..\..\%APPVEYOR_PROJECT_NAME%-pr%APPVEYOR_BUILD_NUMBER%.7z .

deploy:
  - provider: Environment
    name: GHpr

# on successful build
on_success:
  - cmd: echo OK build

# on build failure
on_failure:
  - cmd: echo build FAILED

# after build failure or success
on_finish:
  - cmd: echo DONE
