version: "{build}"

branches:
  only:
    - master

only_commits:
  message: /^\+/
  author: dejbug@users.noreply.github.com

test: off

clone_folder: c:\projects\$(appveyor_project_name)
shallow_clone: true
max_jobs: 1

cache:
  - c:\projects\$(appveyor_project_name)

# scripts that run after cloning repository
install:

# to run your custom scripts instead of automatic MSBuild
build_script:
  - cmd: echo %APPVEYOR_API_URL%
  - cmd: set APPVEYOR_SAVE_CACHE_ON_ERROR=true
  - cmd: set PATH=C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32\bin;%PATH%
  - cmd: mingw32-make --version | head -1
  - cmd: g++ --version | head -1
  - cmd: ar --version | head -1
  - cmd: cd build\msw
  - cmd: python -c "file = open('makefile.gcc', 'rb'); lines = (line.strip('\r\n') for line in file); import re; is_ar = lambda line:re.match(r'(?m)^^[ \t]*(?:ar *rcu|ranlib *).*', line); lines = (line for line in lines if not is_ar(line)); open('makefile2.gcc', 'wb').write('\n'.join(lines))"
  - cmd: mingw32-make -j1 --keep-going -f makefile2.gcc __OPTIMIZEFLAG=-Os CPPFLAGS=-Wno-deprecated-declarations CXXFLAGS=-std=c++11 SHARED=0 UNICODE=1 BUILD=release VENDOR=dejbug SHELL=cmd.exe
  - cmd: echo libwxmsw31u.a :$(wildcard gcc_mswu/*.o) ; ar rcus $@ $(subst /,\,$^^) > monolib.makefile
  - cmd: mingw32-make -j1 -f monolib.makefile SHELL=cmd.exe
  - cmd: python -c "import os,re; n = '%APPVEYOR_PROJECT_NAME%-' + re.search(r'(?m)^ *DYLIB_CURRENT_VERSION += +(.+) *$', open('..\osx\wxvers.xcconfig').read()).group(1); os.mkdir(n)"
  - cmd: cd wxWidgets-*
  - cmd: move ..\..\..\include .
  - cmd: mkdir lib
  - cmd: move ..\*.a lib
  - cmd: move ..\..\..\lib\gcc_lib\mswu lib
  - cmd: 7z a ..\..\..\%APPVEYOR_PROJECT_NAME%-pr%APPVEYOR_BUILD_NUMBER%.7z .

deploy:
  - provider: Environment
    name: GHpr

# on successful build
on_success:
  - cmd: echo OK build

# on build failure
on_failure:
  - cmd: echo build FAILED

# after build failure or success
on_finish:
  - cmd: mingw32-make -j1 --keep-going -f makefile2.gcc __OPTIMIZEFLAG=-Os CPPFLAGS=-Wno-deprecated-declarations CXXFLAGS=-std=c++11 SHARED=0 UNICODE=1 BUILD=release VENDOR=dejbug SHELL=cmd.exe clean
  - cmd: echo DONE
